export const GET_BASIC_ANALYTICS_REQUEST = "GET_BASIC_ANALYTICS_REQUEST";
export const GET_BASIC_ANALYTICS_SUCCESS = "GET_BASIC_ANALYTICS_SUCCESS";
export const GET_BASIC_ANALYTICS_FAIL = "GET_BASIC_ANALYTICS_FAIL";

export const GET_PERFORMANCE_ANALYTICS_REQUEST = "GET_PERFORMANCE_ANALYTICS_REQUEST";
export const GET_PERFORMANCE_ANALYTICS_SUCCESS = "GET_PERFORMANCE_ANALYTICS_SUCCESS";
export const GET_PERFORMANCE_ANALYTICS_FAIL = "GET_PERFORMANCE_ANALYTICS_FAIL";



export const GET_ERROR_ANALYTICS_REQUEST = 'GET_ERROR_ANALYTICS_REQUEST';
export const GET_ERROR_ANALYTICS_SUCCESS = 'GET_ERROR_ANALYTICS_SUCCESS';
export const GET_ERROR_ANALYTICS_FAIL = 'GET_ERROR_ANALYTICS_FAIL';
